"""remove email property from user

Revision ID: 185ce5358b57
Revises: fc5427cdfa48
Create Date: 2025-01-15 19:11:24.432937

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '185ce5358b57'
down_revision = 'fc5427cdfa48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=150), nullable=False))
        batch_op.create_index('email', ['email'], unique=True)

    # ### end Alembic commands ###
